version: '3.9'

services:
  web:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app             # Mount the project folder into the container
      - /app/node_modules  # Prevent node_modules on host from conflicting
    ports:
      - "3000:3000"        # Expose Next.js app on localhost:3000
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    command: sh -c "npm install && npm run dev"  # Install dependencies and start dev server
    restart: unless-stopped
    depends_on:
      - db                 # Start database container before the web app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"        # Expose PostgreSQL on localhost:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    restart: unless-stopped

volumes:
  postgres_data:  # Named volume for PostgreSQL data
