version: '3.9'

services:
  web:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV_PROD}
      - DATABASE_URL=${DATABASE_URL_PROD}
    command: sh -c "npm install && npm run build && npm start"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRES_DB=${POSTGRES_DB_PROD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
