version: '3.9'

services:
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV_PROD}
      - DATABASE_URL=${DATABASE_URL_PROD}
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm start"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRES_DB=${POSTGRES_DB_PROD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
